\set ON_ERROR_STOP on

BEGIN;

CREATE TEMP TABLE jshopping_parts_stage (
    id TEXT,
    name TEXT,
    quantity TEXT,
    description TEXT,
    category TEXT,
    price TEXT,
    salesman TEXT,
    location TEXT,
    address TEXT,
    status TEXT,
    brand TEXT,
    model TEXT,
    photos TEXT,
    seller_id TEXT,
    vin TEXT,
    body_brand TEXT,
    engine_brand TEXT,
    car_release_date TEXT,
    front_rear TEXT,
    left_right TEXT,
    top_bottom TEXT,
    number TEXT,
    manufacturer TEXT,
    manufacturer_code TEXT,
    oem_code TEXT,
    color TEXT,
    condition TEXT,
    supplier_code TEXT,
    defect TEXT,
    transmission TEXT,
    transmission_model TEXT,
    drive TEXT,
    wear_percentage TEXT,
    season TEXT,
    diameter TEXT,
    width TEXT,
    profile TEXT,
    tire_quantity TEXT,
    drilling TEXT,
    "offset" TEXT,
    center_hole_diameter TEXT,
    tire_model TEXT,
    created_at TEXT,
    updated_at TEXT
) ON COMMIT DROP;

\copy jshopping_parts_stage FROM '/tmp/joomshopping_parts.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')

INSERT INTO parts (
    id, name, quantity, description, category, price, salesman, location, address, status,
    brand, model, photos, seller_id, vin, body_brand, engine_brand, car_release_date,
    front_rear, left_right, top_bottom, number, manufacturer, manufacturer_code,
    oem_code, color, condition, supplier_code, defect, transmission, transmission_model,
    drive, wear_percentage, season, diameter, width, profile, tire_quantity, drilling,
    "offset", center_hole_diameter, tire_model, created_at, updated_at
)
SELECT
    id::BIGINT,
    COALESCE(name, ''),
    COALESCE(NULLIF(quantity, ''), '0')::INTEGER,
    COALESCE(description, ''),
    COALESCE(category, ''),
    COALESCE(NULLIF(price, ''), '0')::DOUBLE PRECISION,
    COALESCE(salesman, ''),
    COALESCE(location, ''),
    COALESCE(address, ''),
    COALESCE(NULLIF(status, ''), 'false')::BOOLEAN,
    COALESCE(brand, ''),
    COALESCE(model, ''),
    COALESCE(NULLIF(photos, ''), '[]')::JSONB,
    COALESCE(NULLIF(seller_id, ''), '0')::BIGINT,
    COALESCE(NULLIF(vin, ''), body_brand, ''),
    '',
    COALESCE(engine_brand, ''),
    COALESCE(car_release_date, ''),
    COALESCE(front_rear, ''),
    COALESCE(left_right, ''),
    COALESCE(top_bottom, ''),
    COALESCE(number, ''),
    COALESCE(manufacturer, ''),
    COALESCE(manufacturer_code, ''),
    COALESCE(oem_code, ''),
    COALESCE(color, ''),
    COALESCE(condition, ''),
    COALESCE(supplier_code, ''),
    COALESCE(defect, ''),
    COALESCE(transmission, ''),
    COALESCE(transmission_model, ''),
    COALESCE(drive, ''),
    COALESCE(wear_percentage, ''),
    COALESCE(season, ''),
    COALESCE(diameter, ''),
    COALESCE(width, ''),
    COALESCE(profile, ''),
    COALESCE(tire_quantity, ''),
    COALESCE(drilling, ''),
    COALESCE("offset", ''),
    COALESCE(center_hole_diameter, ''),
    COALESCE(tire_model, ''),
    COALESCE(NULLIF(created_at, ''), NOW()::TEXT)::TIMESTAMPTZ,
    COALESCE(NULLIF(updated_at, ''), NULLIF(created_at, ''), NOW()::TEXT)::TIMESTAMPTZ
FROM jshopping_parts_stage
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    quantity = EXCLUDED.quantity,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    price = EXCLUDED.price,
    salesman = EXCLUDED.salesman,
    location = EXCLUDED.location,
    address = EXCLUDED.address,
    status = EXCLUDED.status,
    brand = EXCLUDED.brand,
    model = EXCLUDED.model,
    -- Photos are imported separately so a data-only refresh never erases them.
    seller_id = EXCLUDED.seller_id,
    vin = EXCLUDED.vin,
    body_brand = EXCLUDED.body_brand,
    engine_brand = EXCLUDED.engine_brand,
    car_release_date = EXCLUDED.car_release_date,
    front_rear = EXCLUDED.front_rear,
    left_right = EXCLUDED.left_right,
    top_bottom = EXCLUDED.top_bottom,
    number = EXCLUDED.number,
    manufacturer = EXCLUDED.manufacturer,
    manufacturer_code = EXCLUDED.manufacturer_code,
    oem_code = EXCLUDED.oem_code,
    color = EXCLUDED.color,
    condition = EXCLUDED.condition,
    supplier_code = EXCLUDED.supplier_code,
    defect = EXCLUDED.defect,
    transmission = EXCLUDED.transmission,
    transmission_model = EXCLUDED.transmission_model,
    drive = EXCLUDED.drive,
    wear_percentage = EXCLUDED.wear_percentage,
    season = EXCLUDED.season,
    diameter = EXCLUDED.diameter,
    width = EXCLUDED.width,
    profile = EXCLUDED.profile,
    tire_quantity = EXCLUDED.tire_quantity,
    drilling = EXCLUDED.drilling,
    "offset" = EXCLUDED."offset",
    center_hole_diameter = EXCLUDED.center_hole_diameter,
    tire_model = EXCLUDED.tire_model,
    created_at = EXCLUDED.created_at,
    updated_at = EXCLUDED.updated_at,
    deleted_at = NULL;

SELECT setval(
    pg_get_serial_sequence('parts', 'id'),
    GREATEST(COALESCE((SELECT MAX(id) FROM parts), 1), 1),
    (SELECT COUNT(*) > 0 FROM parts)
);

COMMIT;
