// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Conversation struct {
	ID            int64              `json:"id"`
	Participants  []int64            `json:"participants"`
	Title         string             `json:"title"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	LastMessageAt pgtype.Timestamptz `json:"last_message_at"`
	LastMessage   string             `json:"last_message"`
}

type Mention struct {
	ID         int64  `json:"id"`
	MessageID  int64  `json:"message_id"`
	Type       string `json:"type"`
	ResourceID int64  `json:"resource_id"`
	Text       string `json:"text"`
}

type Message struct {
	ID             int64              `json:"id"`
	ConversationID int64              `json:"conversation_id"`
	SenderID       int64              `json:"sender_id"`
	Content        string             `json:"content"`
	MessageType    string             `json:"message_type"`
	VoiceUrl       string             `json:"voice_url"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ReadBy         []int64            `json:"read_by"`
	Attachments    []string           `json:"attachments"`
	SearchVector   interface{}        `json:"search_vector"`
}

type Notification struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	Type      string             `json:"type"`
	Message   string             `json:"message"`
	Read      bool               `json:"read"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	RelatedID int64              `json:"related_id"`
}

type Reaction struct {
	ID        int64  `json:"id"`
	MessageID int64  `json:"message_id"`
	UserID    int64  `json:"user_id"`
	Emoji     string `json:"emoji"`
}

type UserStatus struct {
	ID       int64              `json:"id"`
	UserID   int64              `json:"user_id"`
	IsOnline bool               `json:"is_online"`
	LastSeen pgtype.Timestamptz `json:"last_seen"`
}
