// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const AddUserToReadBy = `-- name: AddUserToReadBy :exec
UPDATE messages
SET read_by = array_append(read_by, $1::bigint)
WHERE id = $2 AND NOT (read_by @> ARRAY[$1::bigint])
`

type AddUserToReadByParams struct {
	UserID    int64 `json:"user_id"`
	MessageID int64 `json:"message_id"`
}

func (q *Queries) AddUserToReadBy(ctx context.Context, arg AddUserToReadByParams) error {
	_, err := q.db.Exec(ctx, AddUserToReadBy, arg.UserID, arg.MessageID)
	return err
}

const CreateConversation = `-- name: CreateConversation :one
INSERT INTO conversations (participants, title, created_at, last_message_at, last_message)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, participants, title, created_at, last_message_at, last_message
`

type CreateConversationParams struct {
	Participants  []int64            `json:"participants"`
	Title         string             `json:"title"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	LastMessageAt pgtype.Timestamptz `json:"last_message_at"`
	LastMessage   string             `json:"last_message"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, CreateConversation,
		arg.Participants,
		arg.Title,
		arg.CreatedAt,
		arg.LastMessageAt,
		arg.LastMessage,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Participants,
		&i.Title,
		&i.CreatedAt,
		&i.LastMessageAt,
		&i.LastMessage,
	)
	return i, err
}

const CreateMention = `-- name: CreateMention :one
INSERT INTO mentions (message_id, type, resource_id, text)
VALUES ($1, $2, $3, $4)
RETURNING id, message_id, type, resource_id, text
`

type CreateMentionParams struct {
	MessageID  int64  `json:"message_id"`
	Type       string `json:"type"`
	ResourceID int64  `json:"resource_id"`
	Text       string `json:"text"`
}

func (q *Queries) CreateMention(ctx context.Context, arg CreateMentionParams) (Mention, error) {
	row := q.db.QueryRow(ctx, CreateMention,
		arg.MessageID,
		arg.Type,
		arg.ResourceID,
		arg.Text,
	)
	var i Mention
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.Type,
		&i.ResourceID,
		&i.Text,
	)
	return i, err
}

const CreateMessage = `-- name: CreateMessage :one
INSERT INTO messages (conversation_id, sender_id, content, message_type, voice_url, created_at, read_by, attachments)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, conversation_id, sender_id, content, message_type, voice_url, created_at, read_by, attachments, search_vector
`

type CreateMessageParams struct {
	ConversationID int64              `json:"conversation_id"`
	SenderID       int64              `json:"sender_id"`
	Content        string             `json:"content"`
	MessageType    string             `json:"message_type"`
	VoiceUrl       string             `json:"voice_url"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ReadBy         []int64            `json:"read_by"`
	Attachments    []string           `json:"attachments"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, CreateMessage,
		arg.ConversationID,
		arg.SenderID,
		arg.Content,
		arg.MessageType,
		arg.VoiceUrl,
		arg.CreatedAt,
		arg.ReadBy,
		arg.Attachments,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Content,
		&i.MessageType,
		&i.VoiceUrl,
		&i.CreatedAt,
		&i.ReadBy,
		&i.Attachments,
		&i.SearchVector,
	)
	return i, err
}

const CreateNotification = `-- name: CreateNotification :one
INSERT INTO notifications (user_id, type, message, read, created_at, related_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, type, message, read, created_at, related_id
`

type CreateNotificationParams struct {
	UserID    int64              `json:"user_id"`
	Type      string             `json:"type"`
	Message   string             `json:"message"`
	Read      bool               `json:"read"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	RelatedID int64              `json:"related_id"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, CreateNotification,
		arg.UserID,
		arg.Type,
		arg.Message,
		arg.Read,
		arg.CreatedAt,
		arg.RelatedID,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Message,
		&i.Read,
		&i.CreatedAt,
		&i.RelatedID,
	)
	return i, err
}

const CreateReaction = `-- name: CreateReaction :one
INSERT INTO reactions (message_id, user_id, emoji)
VALUES ($1, $2, $3)
RETURNING id, message_id, user_id, emoji
`

type CreateReactionParams struct {
	MessageID int64  `json:"message_id"`
	UserID    int64  `json:"user_id"`
	Emoji     string `json:"emoji"`
}

func (q *Queries) CreateReaction(ctx context.Context, arg CreateReactionParams) (Reaction, error) {
	row := q.db.QueryRow(ctx, CreateReaction, arg.MessageID, arg.UserID, arg.Emoji)
	var i Reaction
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.UserID,
		&i.Emoji,
	)
	return i, err
}

const DeleteConversation = `-- name: DeleteConversation :exec
DELETE FROM conversations
WHERE id = $1
`

func (q *Queries) DeleteConversation(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, DeleteConversation, id)
	return err
}

const DeleteMessage = `-- name: DeleteMessage :exec
DELETE FROM messages
WHERE id = $1
`

func (q *Queries) DeleteMessage(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, DeleteMessage, id)
	return err
}

const DeleteMessagesByConversationID = `-- name: DeleteMessagesByConversationID :exec
DELETE FROM messages
WHERE conversation_id = $1
`

func (q *Queries) DeleteMessagesByConversationID(ctx context.Context, conversationID int64) error {
	_, err := q.db.Exec(ctx, DeleteMessagesByConversationID, conversationID)
	return err
}

const DeleteReaction = `-- name: DeleteReaction :exec
DELETE FROM reactions
WHERE id = $1
`

func (q *Queries) DeleteReaction(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, DeleteReaction, id)
	return err
}

const DeleteReactionByFields = `-- name: DeleteReactionByFields :exec
DELETE FROM reactions
WHERE message_id = $1 AND user_id = $2 AND emoji = $3
`

type DeleteReactionByFieldsParams struct {
	MessageID int64  `json:"message_id"`
	UserID    int64  `json:"user_id"`
	Emoji     string `json:"emoji"`
}

func (q *Queries) DeleteReactionByFields(ctx context.Context, arg DeleteReactionByFieldsParams) error {
	_, err := q.db.Exec(ctx, DeleteReactionByFields, arg.MessageID, arg.UserID, arg.Emoji)
	return err
}

const GetConversation = `-- name: GetConversation :one
SELECT id, participants, title, created_at, last_message_at, last_message FROM conversations
WHERE id = $1
`

func (q *Queries) GetConversation(ctx context.Context, id int64) (Conversation, error) {
	row := q.db.QueryRow(ctx, GetConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Participants,
		&i.Title,
		&i.CreatedAt,
		&i.LastMessageAt,
		&i.LastMessage,
	)
	return i, err
}

const GetConversations = `-- name: GetConversations :many
SELECT c.id, c.participants, c.title, c.created_at, c.last_message_at, c.last_message, COALESCE(u.unread_count, 0)::bigint as unread_count
FROM conversations c
LEFT JOIN (
    SELECT m.conversation_id, COUNT(*) as unread_count
    FROM messages m
    WHERE NOT (m.read_by @> ARRAY[$1::bigint])
      AND m.sender_id != $1::bigint
    GROUP BY m.conversation_id
) u ON u.conversation_id = c.id
WHERE c.participants @> ARRAY[$1::bigint]
ORDER BY c.last_message_at DESC
`

type GetConversationsRow struct {
	ID            int64              `json:"id"`
	Participants  []int64            `json:"participants"`
	Title         string             `json:"title"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	LastMessageAt pgtype.Timestamptz `json:"last_message_at"`
	LastMessage   string             `json:"last_message"`
	UnreadCount   int64              `json:"unread_count"`
}

func (q *Queries) GetConversations(ctx context.Context, userID int64) ([]GetConversationsRow, error) {
	rows, err := q.db.Query(ctx, GetConversations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetConversationsRow{}
	for rows.Next() {
		var i GetConversationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Participants,
			&i.Title,
			&i.CreatedAt,
			&i.LastMessageAt,
			&i.LastMessage,
			&i.UnreadCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetMentionsByMessageIDs = `-- name: GetMentionsByMessageIDs :many
SELECT id, message_id, type, resource_id, text FROM mentions
WHERE message_id = ANY($1::bigint[])
`

func (q *Queries) GetMentionsByMessageIDs(ctx context.Context, dollar_1 []int64) ([]Mention, error) {
	rows, err := q.db.Query(ctx, GetMentionsByMessageIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Mention{}
	for rows.Next() {
		var i Mention
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.Type,
			&i.ResourceID,
			&i.Text,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetMessagesByConversationID = `-- name: GetMessagesByConversationID :many
SELECT id, conversation_id, sender_id, content, message_type, voice_url, created_at, read_by, attachments, search_vector FROM messages
WHERE conversation_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetMessagesByConversationID(ctx context.Context, conversationID int64) ([]Message, error) {
	rows, err := q.db.Query(ctx, GetMessagesByConversationID, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.Content,
			&i.MessageType,
			&i.VoiceUrl,
			&i.CreatedAt,
			&i.ReadBy,
			&i.Attachments,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetNotificationsByUserID = `-- name: GetNotificationsByUserID :many
SELECT id, user_id, type, message, read, created_at, related_id FROM notifications
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetNotificationsByUserID(ctx context.Context, userID int64) ([]Notification, error) {
	rows, err := q.db.Query(ctx, GetNotificationsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Message,
			&i.Read,
			&i.CreatedAt,
			&i.RelatedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetReactionByID = `-- name: GetReactionByID :one
SELECT id, message_id, user_id, emoji FROM reactions
WHERE id = $1
`

func (q *Queries) GetReactionByID(ctx context.Context, id int64) (Reaction, error) {
	row := q.db.QueryRow(ctx, GetReactionByID, id)
	var i Reaction
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.UserID,
		&i.Emoji,
	)
	return i, err
}

const GetReactionsByMessageIDs = `-- name: GetReactionsByMessageIDs :many
SELECT id, message_id, user_id, emoji FROM reactions
WHERE message_id = ANY($1::bigint[])
`

func (q *Queries) GetReactionsByMessageIDs(ctx context.Context, dollar_1 []int64) ([]Reaction, error) {
	rows, err := q.db.Query(ctx, GetReactionsByMessageIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reaction{}
	for rows.Next() {
		var i Reaction
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.UserID,
			&i.Emoji,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetUserStatusByUserID = `-- name: GetUserStatusByUserID :one
SELECT id, user_id, is_online, last_seen FROM user_status
WHERE user_id = $1
`

func (q *Queries) GetUserStatusByUserID(ctx context.Context, userID int64) (UserStatus, error) {
	row := q.db.QueryRow(ctx, GetUserStatusByUserID, userID)
	var i UserStatus
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IsOnline,
		&i.LastSeen,
	)
	return i, err
}

const GetUserStatuses = `-- name: GetUserStatuses :many
SELECT id, user_id, is_online, last_seen FROM user_status
`

func (q *Queries) GetUserStatuses(ctx context.Context) ([]UserStatus, error) {
	rows, err := q.db.Query(ctx, GetUserStatuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserStatus{}
	for rows.Next() {
		var i UserStatus
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.IsOnline,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const MarkAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications
SET read = TRUE
WHERE user_id = $1
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, MarkAllNotificationsRead, userID)
	return err
}

const MarkNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications
SET read = TRUE
WHERE id = $1
`

func (q *Queries) MarkNotificationRead(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, MarkNotificationRead, id)
	return err
}

const SearchMessagesAll = `-- name: SearchMessagesAll :many
SELECT m.id, m.conversation_id, m.sender_id, m.content, m.message_type, m.voice_url, m.created_at, m.read_by, m.attachments, m.search_vector FROM messages m
WHERE (m.search_vector @@ plainto_tsquery('russian', $3::text) OR m.content ILIKE '%' || $3::text || '%')
ORDER BY m.created_at DESC
LIMIT $1 OFFSET $2
`

type SearchMessagesAllParams struct {
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
	Query  string `json:"query"`
}

func (q *Queries) SearchMessagesAll(ctx context.Context, arg SearchMessagesAllParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, SearchMessagesAll, arg.Limit, arg.Offset, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.Content,
			&i.MessageType,
			&i.VoiceUrl,
			&i.CreatedAt,
			&i.ReadBy,
			&i.Attachments,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SearchMessagesWithUser = `-- name: SearchMessagesWithUser :many
SELECT m.id, m.conversation_id, m.sender_id, m.content, m.message_type, m.voice_url, m.created_at, m.read_by, m.attachments, m.search_vector FROM messages m
JOIN conversations c ON m.conversation_id = c.id
WHERE c.participants @> ARRAY[$3::bigint]
  AND (m.search_vector @@ plainto_tsquery('russian', $4::text) OR m.content ILIKE '%' || $4::text || '%')
ORDER BY m.created_at DESC
LIMIT $1 OFFSET $2
`

type SearchMessagesWithUserParams struct {
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
	UserID int64  `json:"user_id"`
	Query  string `json:"query"`
}

func (q *Queries) SearchMessagesWithUser(ctx context.Context, arg SearchMessagesWithUserParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, SearchMessagesWithUser,
		arg.Limit,
		arg.Offset,
		arg.UserID,
		arg.Query,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.Content,
			&i.MessageType,
			&i.VoiceUrl,
			&i.CreatedAt,
			&i.ReadBy,
			&i.Attachments,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateConversation = `-- name: UpdateConversation :one
UPDATE conversations
SET title = $2,
    last_message_at = $3,
    last_message = $4,
    participants = $5
WHERE id = $1
RETURNING id, participants, title, created_at, last_message_at, last_message
`

type UpdateConversationParams struct {
	ID            int64              `json:"id"`
	Title         string             `json:"title"`
	LastMessageAt pgtype.Timestamptz `json:"last_message_at"`
	LastMessage   string             `json:"last_message"`
	Participants  []int64            `json:"participants"`
}

func (q *Queries) UpdateConversation(ctx context.Context, arg UpdateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, UpdateConversation,
		arg.ID,
		arg.Title,
		arg.LastMessageAt,
		arg.LastMessage,
		arg.Participants,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Participants,
		&i.Title,
		&i.CreatedAt,
		&i.LastMessageAt,
		&i.LastMessage,
	)
	return i, err
}

const UpdateConversationLastMessage = `-- name: UpdateConversationLastMessage :exec
UPDATE conversations
SET last_message_at = $2,
    last_message = $3
WHERE id = $1
`

type UpdateConversationLastMessageParams struct {
	ID            int64              `json:"id"`
	LastMessageAt pgtype.Timestamptz `json:"last_message_at"`
	LastMessage   string             `json:"last_message"`
}

func (q *Queries) UpdateConversationLastMessage(ctx context.Context, arg UpdateConversationLastMessageParams) error {
	_, err := q.db.Exec(ctx, UpdateConversationLastMessage, arg.ID, arg.LastMessageAt, arg.LastMessage)
	return err
}

const UpsertUserStatus = `-- name: UpsertUserStatus :one
INSERT INTO user_status (user_id, is_online, last_seen)
VALUES ($1, $2, $3)
ON CONFLICT (user_id)
DO UPDATE SET is_online = EXCLUDED.is_online,
              last_seen = EXCLUDED.last_seen
RETURNING id, user_id, is_online, last_seen
`

type UpsertUserStatusParams struct {
	UserID   int64              `json:"user_id"`
	IsOnline bool               `json:"is_online"`
	LastSeen pgtype.Timestamptz `json:"last_seen"`
}

func (q *Queries) UpsertUserStatus(ctx context.Context, arg UpsertUserStatusParams) (UserStatus, error) {
	row := q.db.QueryRow(ctx, UpsertUserStatus, arg.UserID, arg.IsOnline, arg.LastSeen)
	var i UserStatus
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IsOnline,
		&i.LastSeen,
	)
	return i, err
}
