// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID          int64              `json:"id"`
	CustomerID  int64              `json:"customer_id"`
	SellerID    int64              `json:"seller_id"`
	Seller      string             `json:"seller"`
	Part        string             `json:"part"`
	PartID      int64              `json:"part_id"`
	Location    string             `json:"location"`
	BuyerNumber string             `json:"buyer_number"`
	Status      string             `json:"status"`
	StatusText  string             `json:"status_text"`
	AutoDeleted bool               `json:"auto_deleted"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type OrderItem struct {
	ID       int64   `json:"id"`
	OrderID  int64   `json:"order_id"`
	PartID   int64   `json:"part_id"`
	Quantity int32   `json:"quantity"`
	Price    float64 `json:"price"`
}

type SalesHistory struct {
	ID        int64              `json:"id"`
	Month     string             `json:"month"`
	Sales     float64            `json:"sales"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
