// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CreateOrder = `-- name: CreateOrder :one
INSERT INTO orders (customer_id, seller_id, seller, part, part_id, location, buyer_number, status, status_text, auto_deleted, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, customer_id, seller_id, seller, part, part_id, location, buyer_number, status, status_text, auto_deleted, created_at
`

type CreateOrderParams struct {
	CustomerID  int64              `json:"customer_id"`
	SellerID    int64              `json:"seller_id"`
	Seller      string             `json:"seller"`
	Part        string             `json:"part"`
	PartID      int64              `json:"part_id"`
	Location    string             `json:"location"`
	BuyerNumber string             `json:"buyer_number"`
	Status      string             `json:"status"`
	StatusText  string             `json:"status_text"`
	AutoDeleted bool               `json:"auto_deleted"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, CreateOrder,
		arg.CustomerID,
		arg.SellerID,
		arg.Seller,
		arg.Part,
		arg.PartID,
		arg.Location,
		arg.BuyerNumber,
		arg.Status,
		arg.StatusText,
		arg.AutoDeleted,
		arg.CreatedAt,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.SellerID,
		&i.Seller,
		&i.Part,
		&i.PartID,
		&i.Location,
		&i.BuyerNumber,
		&i.Status,
		&i.StatusText,
		&i.AutoDeleted,
		&i.CreatedAt,
	)
	return i, err
}

const CreateOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (order_id, part_id, quantity, price)
VALUES ($1, $2, $3, $4)
RETURNING id, order_id, part_id, quantity, price
`

type CreateOrderItemParams struct {
	OrderID  int64   `json:"order_id"`
	PartID   int64   `json:"part_id"`
	Quantity int32   `json:"quantity"`
	Price    float64 `json:"price"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, CreateOrderItem,
		arg.OrderID,
		arg.PartID,
		arg.Quantity,
		arg.Price,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.PartID,
		&i.Quantity,
		&i.Price,
	)
	return i, err
}

const CreateSalesHistory = `-- name: CreateSalesHistory :one
INSERT INTO sales_history (month, sales, created_at)
VALUES ($1, $2, $3)
RETURNING id, month, sales, created_at
`

type CreateSalesHistoryParams struct {
	Month     string             `json:"month"`
	Sales     float64            `json:"sales"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateSalesHistory(ctx context.Context, arg CreateSalesHistoryParams) (SalesHistory, error) {
	row := q.db.QueryRow(ctx, CreateSalesHistory, arg.Month, arg.Sales, arg.CreatedAt)
	var i SalesHistory
	err := row.Scan(
		&i.ID,
		&i.Month,
		&i.Sales,
		&i.CreatedAt,
	)
	return i, err
}

const DeleteOrder = `-- name: DeleteOrder :exec
DELETE FROM orders
WHERE id = $1
`

func (q *Queries) DeleteOrder(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, DeleteOrder, id)
	return err
}

const DeleteOrderItemsByOrderID = `-- name: DeleteOrderItemsByOrderID :exec
DELETE FROM order_items
WHERE order_id = $1
`

func (q *Queries) DeleteOrderItemsByOrderID(ctx context.Context, orderID int64) error {
	_, err := q.db.Exec(ctx, DeleteOrderItemsByOrderID, orderID)
	return err
}

const FindAllOrders = `-- name: FindAllOrders :many
SELECT id, customer_id, seller_id, seller, part, part_id, location, buyer_number, status, status_text, auto_deleted, created_at FROM orders
WHERE auto_deleted = FALSE
ORDER BY created_at DESC
`

func (q *Queries) FindAllOrders(ctx context.Context) ([]Order, error) {
	rows, err := q.db.Query(ctx, FindAllOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.SellerID,
			&i.Seller,
			&i.Part,
			&i.PartID,
			&i.Location,
			&i.BuyerNumber,
			&i.Status,
			&i.StatusText,
			&i.AutoDeleted,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const FindOrderItem = `-- name: FindOrderItem :one
SELECT id, order_id, part_id, quantity, price FROM order_items
WHERE order_id = $1 AND part_id = $2
`

type FindOrderItemParams struct {
	OrderID int64 `json:"order_id"`
	PartID  int64 `json:"part_id"`
}

func (q *Queries) FindOrderItem(ctx context.Context, arg FindOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, FindOrderItem, arg.OrderID, arg.PartID)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.PartID,
		&i.Quantity,
		&i.Price,
	)
	return i, err
}

const GetMonthlySales = `-- name: GetMonthlySales :many
SELECT TO_CHAR(orders.created_at, 'YYYY-MM')::text as month,
       COALESCE(SUM(order_items.price * order_items.quantity), 0)::double precision as sales
FROM order_items
JOIN orders ON order_items.order_id = orders.id
WHERE orders.status = 'green' AND orders.auto_deleted = TRUE
GROUP BY TO_CHAR(orders.created_at, 'YYYY-MM')
ORDER BY month DESC
`

type GetMonthlySalesRow struct {
	Month string  `json:"month"`
	Sales float64 `json:"sales"`
}

func (q *Queries) GetMonthlySales(ctx context.Context) ([]GetMonthlySalesRow, error) {
	rows, err := q.db.Query(ctx, GetMonthlySales)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMonthlySalesRow{}
	for rows.Next() {
		var i GetMonthlySalesRow
		if err := rows.Scan(&i.Month, &i.Sales); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetOrderByID = `-- name: GetOrderByID :one
SELECT id, customer_id, seller_id, seller, part, part_id, location, buyer_number, status, status_text, auto_deleted, created_at FROM orders
WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id int64) (Order, error) {
	row := q.db.QueryRow(ctx, GetOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.SellerID,
		&i.Seller,
		&i.Part,
		&i.PartID,
		&i.Location,
		&i.BuyerNumber,
		&i.Status,
		&i.StatusText,
		&i.AutoDeleted,
		&i.CreatedAt,
	)
	return i, err
}

const GetOrderItemsByOrderID = `-- name: GetOrderItemsByOrderID :many
SELECT id, order_id, part_id, quantity, price FROM order_items
WHERE order_id = $1
`

func (q *Queries) GetOrderItemsByOrderID(ctx context.Context, orderID int64) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, GetOrderItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.PartID,
			&i.Quantity,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetOrderItemsByOrderIDs = `-- name: GetOrderItemsByOrderIDs :many
SELECT id, order_id, part_id, quantity, price FROM order_items
WHERE order_id = ANY($1::bigint[])
`

func (q *Queries) GetOrderItemsByOrderIDs(ctx context.Context, dollar_1 []int64) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, GetOrderItemsByOrderIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.PartID,
			&i.Quantity,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const MarkExpiredAsAutoDeleted = `-- name: MarkExpiredAsAutoDeleted :exec
UPDATE orders
SET auto_deleted = TRUE
WHERE created_at <= $1 AND auto_deleted = FALSE
`

func (q *Queries) MarkExpiredAsAutoDeleted(ctx context.Context, createdAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, MarkExpiredAsAutoDeleted, createdAt)
	return err
}

const UpdateOrderItem = `-- name: UpdateOrderItem :exec
UPDATE order_items
SET quantity = $2,
    price = $3
WHERE id = $1
`

type UpdateOrderItemParams struct {
	ID       int64   `json:"id"`
	Quantity int32   `json:"quantity"`
	Price    float64 `json:"price"`
}

func (q *Queries) UpdateOrderItem(ctx context.Context, arg UpdateOrderItemParams) error {
	_, err := q.db.Exec(ctx, UpdateOrderItem, arg.ID, arg.Quantity, arg.Price)
	return err
}

const UpdateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders
SET status = $2
WHERE id = $1
`

type UpdateOrderStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.Exec(ctx, UpdateOrderStatus, arg.ID, arg.Status)
	return err
}

const UpdateSellerName = `-- name: UpdateSellerName :exec
UPDATE orders
SET seller = $2
WHERE seller_id = $1
`

type UpdateSellerNameParams struct {
	SellerID int64  `json:"seller_id"`
	Seller   string `json:"seller"`
}

func (q *Queries) UpdateSellerName(ctx context.Context, arg UpdateSellerNameParams) error {
	_, err := q.db.Exec(ctx, UpdateSellerName, arg.SellerID, arg.Seller)
	return err
}
