// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CompleteOrderRecord = `-- name: CompleteOrderRecord :exec
UPDATE orders
SET status = 'green',
    status_text = 'Завершён',
    payment_status = 'paid',
    warehouse_status = 'ready',
    auto_deleted = TRUE,
    completed_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) CompleteOrderRecord(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, CompleteOrderRecord, id)
	return err
}

const CreateCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (
    name, phone, city, preferred_tk, passport_or_inn,
    category, discount_percent, notes, created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, name, phone, city, preferred_tk, passport_or_inn, category, discount_percent, notes, created_at, updated_at
`

type CreateCustomerParams struct {
	Name            string             `json:"name"`
	Phone           string             `json:"phone"`
	City            string             `json:"city"`
	PreferredTk     string             `json:"preferred_tk"`
	PassportOrInn   string             `json:"passport_or_inn"`
	Category        string             `json:"category"`
	DiscountPercent float64            `json:"discount_percent"`
	Notes           string             `json:"notes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, CreateCustomer,
		arg.Name,
		arg.Phone,
		arg.City,
		arg.PreferredTk,
		arg.PassportOrInn,
		arg.Category,
		arg.DiscountPercent,
		arg.Notes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.City,
		&i.PreferredTk,
		&i.PassportOrInn,
		&i.Category,
		&i.DiscountPercent,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const CreateOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    customer_id, seller_id, seller, part, part_id, location, buyer_number,
    status, status_text, auto_deleted, created_at,
    order_number, source, payment_status, warehouse_status, delivery_method,
    transport_company, tracking_number, notes, discount, completed_at, updated_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11,
    $12, $13, $14, $15, $16,
    $17, $18, $19, $20, $21, $22
)
RETURNING id, customer_id, seller_id, seller, part, part_id, location, buyer_number, status, status_text, auto_deleted, created_at, order_number, source, payment_status, warehouse_status, delivery_method, transport_company, tracking_number, notes, discount, completed_at, updated_at
`

type CreateOrderParams struct {
	CustomerID       int64              `json:"customer_id"`
	SellerID         int64              `json:"seller_id"`
	Seller           string             `json:"seller"`
	Part             string             `json:"part"`
	PartID           int64              `json:"part_id"`
	Location         string             `json:"location"`
	BuyerNumber      string             `json:"buyer_number"`
	Status           string             `json:"status"`
	StatusText       string             `json:"status_text"`
	AutoDeleted      bool               `json:"auto_deleted"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	OrderNumber      string             `json:"order_number"`
	Source           string             `json:"source"`
	PaymentStatus    string             `json:"payment_status"`
	WarehouseStatus  string             `json:"warehouse_status"`
	DeliveryMethod   string             `json:"delivery_method"`
	TransportCompany string             `json:"transport_company"`
	TrackingNumber   string             `json:"tracking_number"`
	Notes            string             `json:"notes"`
	Discount         float64            `json:"discount"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, CreateOrder,
		arg.CustomerID,
		arg.SellerID,
		arg.Seller,
		arg.Part,
		arg.PartID,
		arg.Location,
		arg.BuyerNumber,
		arg.Status,
		arg.StatusText,
		arg.AutoDeleted,
		arg.CreatedAt,
		arg.OrderNumber,
		arg.Source,
		arg.PaymentStatus,
		arg.WarehouseStatus,
		arg.DeliveryMethod,
		arg.TransportCompany,
		arg.TrackingNumber,
		arg.Notes,
		arg.Discount,
		arg.CompletedAt,
		arg.UpdatedAt,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.SellerID,
		&i.Seller,
		&i.Part,
		&i.PartID,
		&i.Location,
		&i.BuyerNumber,
		&i.Status,
		&i.StatusText,
		&i.AutoDeleted,
		&i.CreatedAt,
		&i.OrderNumber,
		&i.Source,
		&i.PaymentStatus,
		&i.WarehouseStatus,
		&i.DeliveryMethod,
		&i.TransportCompany,
		&i.TrackingNumber,
		&i.Notes,
		&i.Discount,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const CreateOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (order_id, part_id, quantity, price, part_name_snapshot)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, order_id, part_id, quantity, price, part_name_snapshot
`

type CreateOrderItemParams struct {
	OrderID          int64   `json:"order_id"`
	PartID           int64   `json:"part_id"`
	Quantity         int32   `json:"quantity"`
	Price            float64 `json:"price"`
	PartNameSnapshot string  `json:"part_name_snapshot"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, CreateOrderItem,
		arg.OrderID,
		arg.PartID,
		arg.Quantity,
		arg.Price,
		arg.PartNameSnapshot,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.PartID,
		&i.Quantity,
		&i.Price,
		&i.PartNameSnapshot,
	)
	return i, err
}

const CreateSalesHistory = `-- name: CreateSalesHistory :one
INSERT INTO sales_history (month, sales, created_at)
VALUES ($1, $2, $3)
RETURNING id, month, sales, created_at
`

type CreateSalesHistoryParams struct {
	Month     string             `json:"month"`
	Sales     float64            `json:"sales"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateSalesHistory(ctx context.Context, arg CreateSalesHistoryParams) (SalesHistory, error) {
	row := q.db.QueryRow(ctx, CreateSalesHistory, arg.Month, arg.Sales, arg.CreatedAt)
	var i SalesHistory
	err := row.Scan(
		&i.ID,
		&i.Month,
		&i.Sales,
		&i.CreatedAt,
	)
	return i, err
}

const DeleteCustomer = `-- name: DeleteCustomer :exec
DELETE FROM customers
WHERE id = $1
`

func (q *Queries) DeleteCustomer(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, DeleteCustomer, id)
	return err
}

const DeleteOrder = `-- name: DeleteOrder :exec
DELETE FROM orders
WHERE id = $1
`

func (q *Queries) DeleteOrder(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, DeleteOrder, id)
	return err
}

const DeleteOrderItem = `-- name: DeleteOrderItem :exec
DELETE FROM order_items
WHERE id = $1 AND order_id = $2
`

type DeleteOrderItemParams struct {
	ID      int64 `json:"id"`
	OrderID int64 `json:"order_id"`
}

func (q *Queries) DeleteOrderItem(ctx context.Context, arg DeleteOrderItemParams) error {
	_, err := q.db.Exec(ctx, DeleteOrderItem, arg.ID, arg.OrderID)
	return err
}

const DeleteOrderItemsByOrderID = `-- name: DeleteOrderItemsByOrderID :exec
DELETE FROM order_items
WHERE order_id = $1
`

func (q *Queries) DeleteOrderItemsByOrderID(ctx context.Context, orderID int64) error {
	_, err := q.db.Exec(ctx, DeleteOrderItemsByOrderID, orderID)
	return err
}

const FindAllOrders = `-- name: FindAllOrders :many
SELECT id, customer_id, seller_id, seller, part, part_id, location, buyer_number, status, status_text, auto_deleted, created_at, order_number, source, payment_status, warehouse_status, delivery_method, transport_company, tracking_number, notes, discount, completed_at, updated_at FROM orders
WHERE auto_deleted = FALSE
ORDER BY created_at DESC
`

func (q *Queries) FindAllOrders(ctx context.Context) ([]Order, error) {
	rows, err := q.db.Query(ctx, FindAllOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.SellerID,
			&i.Seller,
			&i.Part,
			&i.PartID,
			&i.Location,
			&i.BuyerNumber,
			&i.Status,
			&i.StatusText,
			&i.AutoDeleted,
			&i.CreatedAt,
			&i.OrderNumber,
			&i.Source,
			&i.PaymentStatus,
			&i.WarehouseStatus,
			&i.DeliveryMethod,
			&i.TransportCompany,
			&i.TrackingNumber,
			&i.Notes,
			&i.Discount,
			&i.CompletedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const FindCompletedOrders = `-- name: FindCompletedOrders :many
SELECT id, customer_id, seller_id, seller, part, part_id, location, buyer_number, status, status_text, auto_deleted, created_at, order_number, source, payment_status, warehouse_status, delivery_method, transport_company, tracking_number, notes, discount, completed_at, updated_at FROM orders
WHERE auto_deleted = TRUE
ORDER BY COALESCE(completed_at, created_at) DESC
LIMIT 200
`

func (q *Queries) FindCompletedOrders(ctx context.Context) ([]Order, error) {
	rows, err := q.db.Query(ctx, FindCompletedOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.SellerID,
			&i.Seller,
			&i.Part,
			&i.PartID,
			&i.Location,
			&i.BuyerNumber,
			&i.Status,
			&i.StatusText,
			&i.AutoDeleted,
			&i.CreatedAt,
			&i.OrderNumber,
			&i.Source,
			&i.PaymentStatus,
			&i.WarehouseStatus,
			&i.DeliveryMethod,
			&i.TransportCompany,
			&i.TrackingNumber,
			&i.Notes,
			&i.Discount,
			&i.CompletedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const FindOrderItem = `-- name: FindOrderItem :one
SELECT id, order_id, part_id, quantity, price, part_name_snapshot FROM order_items
WHERE order_id = $1 AND part_id = $2
`

type FindOrderItemParams struct {
	OrderID int64 `json:"order_id"`
	PartID  int64 `json:"part_id"`
}

func (q *Queries) FindOrderItem(ctx context.Context, arg FindOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, FindOrderItem, arg.OrderID, arg.PartID)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.PartID,
		&i.Quantity,
		&i.Price,
		&i.PartNameSnapshot,
	)
	return i, err
}

const GetCustomerByID = `-- name: GetCustomerByID :one
SELECT id, name, phone, city, preferred_tk, passport_or_inn, category, discount_percent, notes, created_at, updated_at FROM customers
WHERE id = $1
`

func (q *Queries) GetCustomerByID(ctx context.Context, id int64) (Customer, error) {
	row := q.db.QueryRow(ctx, GetCustomerByID, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.City,
		&i.PreferredTk,
		&i.PassportOrInn,
		&i.Category,
		&i.DiscountPercent,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetCustomerByPhone = `-- name: GetCustomerByPhone :one
SELECT id, name, phone, city, preferred_tk, passport_or_inn, category, discount_percent, notes, created_at, updated_at FROM customers
WHERE phone = $1
LIMIT 1
`

func (q *Queries) GetCustomerByPhone(ctx context.Context, phone string) (Customer, error) {
	row := q.db.QueryRow(ctx, GetCustomerByPhone, phone)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.City,
		&i.PreferredTk,
		&i.PassportOrInn,
		&i.Category,
		&i.DiscountPercent,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetMonthlySales = `-- name: GetMonthlySales :many
SELECT month, COALESCE(SUM(order_total), 0)::double precision AS sales
FROM (
    SELECT TO_CHAR(COALESCE(orders.completed_at, orders.created_at), 'YYYY-MM')::text AS month,
           GREATEST(COALESCE(SUM(order_items.price * order_items.quantity), 0) - orders.discount, 0)::double precision AS order_total
    FROM orders
    JOIN order_items ON order_items.order_id = orders.id
    WHERE orders.status = 'green' AND orders.auto_deleted = TRUE
    GROUP BY orders.id, orders.completed_at, orders.created_at, orders.discount
) AS completed_orders
GROUP BY month
ORDER BY month DESC
`

type GetMonthlySalesRow struct {
	Month string  `json:"month"`
	Sales float64 `json:"sales"`
}

func (q *Queries) GetMonthlySales(ctx context.Context) ([]GetMonthlySalesRow, error) {
	rows, err := q.db.Query(ctx, GetMonthlySales)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMonthlySalesRow{}
	for rows.Next() {
		var i GetMonthlySalesRow
		if err := rows.Scan(&i.Month, &i.Sales); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetOrderByID = `-- name: GetOrderByID :one
SELECT id, customer_id, seller_id, seller, part, part_id, location, buyer_number, status, status_text, auto_deleted, created_at, order_number, source, payment_status, warehouse_status, delivery_method, transport_company, tracking_number, notes, discount, completed_at, updated_at FROM orders
WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id int64) (Order, error) {
	row := q.db.QueryRow(ctx, GetOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.SellerID,
		&i.Seller,
		&i.Part,
		&i.PartID,
		&i.Location,
		&i.BuyerNumber,
		&i.Status,
		&i.StatusText,
		&i.AutoDeleted,
		&i.CreatedAt,
		&i.OrderNumber,
		&i.Source,
		&i.PaymentStatus,
		&i.WarehouseStatus,
		&i.DeliveryMethod,
		&i.TransportCompany,
		&i.TrackingNumber,
		&i.Notes,
		&i.Discount,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetOrderItemsByOrderID = `-- name: GetOrderItemsByOrderID :many
SELECT id, order_id, part_id, quantity, price, part_name_snapshot FROM order_items
WHERE order_id = $1
ORDER BY id ASC
`

func (q *Queries) GetOrderItemsByOrderID(ctx context.Context, orderID int64) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, GetOrderItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.PartID,
			&i.Quantity,
			&i.Price,
			&i.PartNameSnapshot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetOrderItemsByOrderIDs = `-- name: GetOrderItemsByOrderIDs :many
SELECT id, order_id, part_id, quantity, price, part_name_snapshot FROM order_items
WHERE order_id = ANY($1::bigint[])
ORDER BY id ASC
`

func (q *Queries) GetOrderItemsByOrderIDs(ctx context.Context, dollar_1 []int64) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, GetOrderItemsByOrderIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.PartID,
			&i.Quantity,
			&i.Price,
			&i.PartNameSnapshot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetOrdersByCustomerID = `-- name: GetOrdersByCustomerID :many
SELECT id, customer_id, seller_id, seller, part, part_id, location, buyer_number, status, status_text, auto_deleted, created_at, order_number, source, payment_status, warehouse_status, delivery_method, transport_company, tracking_number, notes, discount, completed_at, updated_at FROM orders
WHERE customer_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetOrdersByCustomerID(ctx context.Context, customerID int64) ([]Order, error) {
	rows, err := q.db.Query(ctx, GetOrdersByCustomerID, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.SellerID,
			&i.Seller,
			&i.Part,
			&i.PartID,
			&i.Location,
			&i.BuyerNumber,
			&i.Status,
			&i.StatusText,
			&i.AutoDeleted,
			&i.CreatedAt,
			&i.OrderNumber,
			&i.Source,
			&i.PaymentStatus,
			&i.WarehouseStatus,
			&i.DeliveryMethod,
			&i.TransportCompany,
			&i.TrackingNumber,
			&i.Notes,
			&i.Discount,
			&i.CompletedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListCustomersWithStats = `-- name: ListCustomersWithStats :many
SELECT c.id, c.name, c.phone, c.city, c.preferred_tk, c.passport_or_inn,
       c.category, c.discount_percent, c.notes, c.created_at, c.updated_at,
       COUNT(o.id)::bigint AS total_orders,
       COALESCE(SUM(CASE WHEN o.auto_deleted = TRUE OR o.status = 'green' THEN order_totals.total ELSE 0 END), 0)::double precision AS total_spent,
       MAX(o.created_at)::timestamptz AS last_order_at
FROM customers c
LEFT JOIN orders o ON o.customer_id = c.id
LEFT JOIN (
    SELECT order_id, SUM(price * quantity) AS total
    FROM order_items
    GROUP BY order_id
) order_totals ON order_totals.order_id = o.id
WHERE ($1::text = '' OR c.category = $1::text)
  AND ($2::text = '' OR 
       c.name ILIKE '%' || $2::text || '%' OR 
       c.phone ILIKE '%' || $2::text || '%' OR 
       c.city ILIKE '%' || $2::text || '%' OR 
       c.preferred_tk ILIKE '%' || $2::text || '%')
GROUP BY c.id
ORDER BY c.updated_at DESC
LIMIT $4::int OFFSET $3::int
`

type ListCustomersWithStatsParams struct {
	Category  string `json:"category"`
	Search    string `json:"search"`
	OffsetVal int32  `json:"offset_val"`
	LimitVal  int32  `json:"limit_val"`
}

type ListCustomersWithStatsRow struct {
	ID              int64              `json:"id"`
	Name            string             `json:"name"`
	Phone           string             `json:"phone"`
	City            string             `json:"city"`
	PreferredTk     string             `json:"preferred_tk"`
	PassportOrInn   string             `json:"passport_or_inn"`
	Category        string             `json:"category"`
	DiscountPercent float64            `json:"discount_percent"`
	Notes           string             `json:"notes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	TotalOrders     int64              `json:"total_orders"`
	TotalSpent      float64            `json:"total_spent"`
	LastOrderAt     pgtype.Timestamptz `json:"last_order_at"`
}

func (q *Queries) ListCustomersWithStats(ctx context.Context, arg ListCustomersWithStatsParams) ([]ListCustomersWithStatsRow, error) {
	rows, err := q.db.Query(ctx, ListCustomersWithStats,
		arg.Category,
		arg.Search,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCustomersWithStatsRow{}
	for rows.Next() {
		var i ListCustomersWithStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.City,
			&i.PreferredTk,
			&i.PassportOrInn,
			&i.Category,
			&i.DiscountPercent,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalOrders,
			&i.TotalSpent,
			&i.LastOrderAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const MarkExpiredAsAutoDeleted = `-- name: MarkExpiredAsAutoDeleted :exec
UPDATE orders
SET auto_deleted = TRUE
WHERE created_at <= $1 AND auto_deleted = FALSE
`

func (q *Queries) MarkExpiredAsAutoDeleted(ctx context.Context, createdAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, MarkExpiredAsAutoDeleted, createdAt)
	return err
}

const UpdateCustomer = `-- name: UpdateCustomer :one
UPDATE customers
SET name = $2,
    phone = $3,
    city = $4,
    preferred_tk = $5,
    passport_or_inn = $6,
    category = $7,
    discount_percent = $8,
    notes = $9,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, phone, city, preferred_tk, passport_or_inn, category, discount_percent, notes, created_at, updated_at
`

type UpdateCustomerParams struct {
	ID              int64   `json:"id"`
	Name            string  `json:"name"`
	Phone           string  `json:"phone"`
	City            string  `json:"city"`
	PreferredTk     string  `json:"preferred_tk"`
	PassportOrInn   string  `json:"passport_or_inn"`
	Category        string  `json:"category"`
	DiscountPercent float64 `json:"discount_percent"`
	Notes           string  `json:"notes"`
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, UpdateCustomer,
		arg.ID,
		arg.Name,
		arg.Phone,
		arg.City,
		arg.PreferredTk,
		arg.PassportOrInn,
		arg.Category,
		arg.DiscountPercent,
		arg.Notes,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.City,
		&i.PreferredTk,
		&i.PassportOrInn,
		&i.Category,
		&i.DiscountPercent,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const UpdateOrderItem = `-- name: UpdateOrderItem :exec
UPDATE order_items
SET quantity = $2,
    price = $3
WHERE id = $1
`

type UpdateOrderItemParams struct {
	ID       int64   `json:"id"`
	Quantity int32   `json:"quantity"`
	Price    float64 `json:"price"`
}

func (q *Queries) UpdateOrderItem(ctx context.Context, arg UpdateOrderItemParams) error {
	_, err := q.db.Exec(ctx, UpdateOrderItem, arg.ID, arg.Quantity, arg.Price)
	return err
}

const UpdateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders
SET status = $2,
    status_text = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateOrderStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.Exec(ctx, UpdateOrderStatus, arg.ID, arg.Status)
	return err
}

const UpdateSellerName = `-- name: UpdateSellerName :exec
UPDATE orders
SET seller = $2
WHERE seller_id = $1
`

type UpdateSellerNameParams struct {
	SellerID int64  `json:"seller_id"`
	Seller   string `json:"seller"`
}

func (q *Queries) UpdateSellerName(ctx context.Context, arg UpdateSellerNameParams) error {
	_, err := q.db.Exec(ctx, UpdateSellerName, arg.SellerID, arg.Seller)
	return err
}
