// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity_logs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CreateActivityLog = `-- name: CreateActivityLog :one
INSERT INTO user_activity_logs (user_id, user_name, user_email, action, resource_type, resource_id, details, ip_address, user_agent)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, user_name, user_email, action, resource_type, resource_id, details, ip_address, user_agent, created_at
`

type CreateActivityLogParams struct {
	UserID       int64       `json:"user_id"`
	UserName     string      `json:"user_name"`
	UserEmail    string      `json:"user_email"`
	Action       string      `json:"action"`
	ResourceType string      `json:"resource_type"`
	ResourceID   pgtype.Int8 `json:"resource_id"`
	Details      pgtype.Text `json:"details"`
	IpAddress    pgtype.Text `json:"ip_address"`
	UserAgent    pgtype.Text `json:"user_agent"`
}

func (q *Queries) CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) (UserActivityLog, error) {
	row := q.db.QueryRow(ctx, CreateActivityLog,
		arg.UserID,
		arg.UserName,
		arg.UserEmail,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Details,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i UserActivityLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UserName,
		&i.UserEmail,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.Details,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}
