// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID       int64  `json:"id"`
	Email    string `json:"email"`
	Name     string `json:"name"`
	Initials string `json:"initials"`
	Inn      string `json:"inn"`
	Provider string `json:"provider"`
	Role     string `json:"role"`
	Password string `json:"password"`
}

type UserActivityLog struct {
	ID           int64              `json:"id"`
	UserID       int64              `json:"user_id"`
	UserName     string             `json:"user_name"`
	UserEmail    string             `json:"user_email"`
	Action       string             `json:"action"`
	ResourceType string             `json:"resource_type"`
	ResourceID   pgtype.Int8        `json:"resource_id"`
	Details      pgtype.Text        `json:"details"`
	IpAddress    pgtype.Text        `json:"ip_address"`
	UserAgent    pgtype.Text        `json:"user_agent"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
