// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
)

const CountAllUsers = `-- name: CountAllUsers :one
SELECT COUNT(*)::BIGINT AS count FROM users
`

func (q *Queries) CountAllUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, CountAllUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateUser = `-- name: CreateUser :one
INSERT INTO users (email, name, initials, inn, provider, role, password)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, email, name, initials, inn, provider, role, password
`

type CreateUserParams struct {
	Email    string `json:"email"`
	Name     string `json:"name"`
	Initials string `json:"initials"`
	Inn      string `json:"inn"`
	Provider string `json:"provider"`
	Role     string `json:"role"`
	Password string `json:"password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, CreateUser,
		arg.Email,
		arg.Name,
		arg.Initials,
		arg.Inn,
		arg.Provider,
		arg.Role,
		arg.Password,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Initials,
		&i.Inn,
		&i.Provider,
		&i.Role,
		&i.Password,
	)
	return i, err
}

const DeleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, DeleteUser, id)
	return err
}

const ExistsByEmail = `-- name: ExistsByEmail :one
SELECT COUNT(*) > 0 AS exists FROM users WHERE email = $1
`

func (q *Queries) ExistsByEmail(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, ExistsByEmail, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const ExistsByName = `-- name: ExistsByName :one
SELECT COUNT(*) > 0 AS exists FROM users WHERE name = $1
`

func (q *Queries) ExistsByName(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRow(ctx, ExistsByName, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const FindAllUsers = `-- name: FindAllUsers :many
SELECT id, email, name, initials, inn, provider, role, password
FROM users
ORDER BY id
`

func (q *Queries) FindAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, FindAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Initials,
			&i.Inn,
			&i.Provider,
			&i.Role,
			&i.Password,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetUserByEmailOrName = `-- name: GetUserByEmailOrName :one
SELECT id, email, name, initials, inn, provider, role, password
FROM users
WHERE email = $1 OR name = $2
LIMIT 1
`

type GetUserByEmailOrNameParams struct {
	Email string `json:"email"`
	Name  string `json:"name"`
}

func (q *Queries) GetUserByEmailOrName(ctx context.Context, arg GetUserByEmailOrNameParams) (User, error) {
	row := q.db.QueryRow(ctx, GetUserByEmailOrName, arg.Email, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Initials,
		&i.Inn,
		&i.Provider,
		&i.Role,
		&i.Password,
	)
	return i, err
}

const GetUserByID = `-- name: GetUserByID :one
SELECT id, email, name, initials, inn, provider, role, password
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, GetUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Initials,
		&i.Inn,
		&i.Provider,
		&i.Role,
		&i.Password,
	)
	return i, err
}

const UpdateUser = `-- name: UpdateUser :exec
UPDATE users
SET
    name = COALESCE(NULLIF($2::text, ''), name),
    email = COALESCE(NULLIF($3::text, ''), email),
    initials = COALESCE(NULLIF($4::text, ''), initials),
    inn = COALESCE(NULLIF($5::text, ''), inn),
    role = COALESCE(NULLIF($6::text, ''), role)
WHERE id = $1
`

type UpdateUserParams struct {
	ID      int64  `json:"id"`
	Column2 string `json:"column_2"`
	Column3 string `json:"column_3"`
	Column4 string `json:"column_4"`
	Column5 string `json:"column_5"`
	Column6 string `json:"column_6"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, UpdateUser,
		arg.ID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
	)
	return err
}
