const fs = require('fs');
const path = require('path');

const EXTENSIONS = new Set([
    '.go', '.ts', '.tsx', '.js', '.jsx', '.dart', '.proto', 
    '.py', '.sh', '.bash', '.sql', '.yaml', '.yml', '.json',
    '.css', '.scss', '.html', '.md', '.conf', 'Dockerfile'
]);

const EXCLUDE_DIRS = new Set([
    'node_modules', 'dist', 'build', '.git', '.idea', '.agents',
    '.claude', '.gemini', '.vscode', '.dart_tool', 'gen', 'bin',
    'postgres-data', 'redis-data', 'prometheus-data', 'grafana-data', 'tempo-data',
    '.gradle', 'Pods'
]);

const EXCLUDE_FILES = new Set([
    'package-lock.json', 'pubspec.lock', 'yarn.lock', 'pnpm-lock.yaml',
    'go.sum', 'main', 'gateway', 'avtoplaneta-backend', 'main.exe',
    'grafana-dashboard.json', 'components.json'
]);

function isGenerated(filepath, content) {
    if (filepath.endsWith('.pb.go') || filepath.endsWith('.pb.gw.go')) return true;
    if (content.includes('Code generated by') || content.includes('DO NOT EDIT') || content.includes('AUTOGENERATED')) return true;
    return false;
}

function walkDir(rootDir) {
    let totalFiles = 0;
    let totalLines = 0;
    let totalCodeLines = 0;
    let totalChars = 0;

    const statsByExt = {};
    const statsByDir = {};

    function scan(dir) {
        const entries = fs.readdirSync(dir, { withFileTypes: true });
        const relPath = path.relative(rootDir, dir);
        const topComp = relPath ? relPath.split(path.sep)[0] : 'root';

        for (const entry of entries) {
            const fullPath = path.join(dir, entry.name);

            if (entry.isDirectory()) {
                if (EXCLUDE_DIRS.has(entry.name) || entry.name.startsWith('.')) continue;
                scan(fullPath);
            } else if (entry.isFile()) {
                if (EXCLUDE_FILES.has(entry.name)) continue;
                let ext = path.extname(entry.name);
                if (!ext && (entry.name === 'Dockerfile' || entry.name === 'Makefile')) ext = entry.name;
                if (!EXTENSIONS.has(ext)) continue;

                try {
                    const content = fs.readFileSync(fullPath, 'utf8');
                    if (isGenerated(fullPath, content)) continue;

                    const lines = content.split(/\r?\n/);
                    const numLines = lines.length;
                    const numChars = content.length;
                    const codeLines = lines.filter(l => {
                        const s = l.trim();
                        return s && !s.startsWith('//') && !s.startsWith('#') && !s.startsWith('/*');
                    }).length;

                    totalFiles++;
                    totalLines += numLines;
                    totalCodeLines += codeLines;
                    totalChars += numChars;

                    if (!statsByExt[ext]) statsByExt[ext] = { files: 0, lines: 0, codeLines: 0, chars: 0 };
                    statsByExt[ext].files++;
                    statsByExt[ext].lines += numLines;
                    statsByExt[ext].codeLines += codeLines;
                    statsByExt[ext].chars += numChars;

                    if (!statsByDir[topComp]) statsByDir[topComp] = { files: 0, lines: 0, codeLines: 0, chars: 0 };
                    statsByDir[topComp].files++;
                    statsByDir[topComp].lines += numLines;
                    statsByDir[topComp].codeLines += codeLines;
                    statsByDir[topComp].chars += numChars;
                } catch (e) {}
            }
        }
    }

    scan(rootDir);

    return { totalFiles, totalLines, totalCodeLines, totalChars, statsByExt, statsByDir };
}

const root = path.resolve(__dirname, '..');
const res = walkDir(root);

console.log("=" .repeat(65));
console.log("      СТАТИСТИКА ИСХОДНОГО КОДА ПРОЕКТА AVTOPLANETA      ");
console.log("=" .repeat(65));
console.log(`Всего авторских файлов:    ${res.totalFiles.toLocaleString()}`);
console.log(`Всего строк (Total Lines): ${res.totalLines.toLocaleString()}`);
console.log(`Чистых строк кода (LOC):   ${res.totalCodeLines.toLocaleString()}`);
console.log(`Всего символов (Chars):    ${res.totalChars.toLocaleString()}`);

console.log("\n--- Разбор по компонентам ---");
Object.entries(res.statsByDir)
    .sort((a, b) => b[1].lines - a[1].lines)
    .forEach(([comp, d]) => {
        console.log(`  • ${comp.padEnd(20)}: ${String(d.files).padStart(3)} файлов | ${String(d.lines.toLocaleString()).padStart(7)} строк | ${String(d.chars.toLocaleString()).padStart(10)} символов`);
    });

console.log("\n--- Разбор по языкам / расширениям ---");
Object.entries(res.statsByExt)
    .sort((a, b) => b[1].lines - a[1].lines)
    .forEach(([ext, d]) => {
        console.log(`  • ${ext.padEnd(12)}: ${String(d.files).padStart(3)} файлов | ${String(d.lines.toLocaleString()).padStart(7)} строк | ${String(d.chars.toLocaleString()).padStart(10)} символов`);
    });
console.log("=" .repeat(65));
