import os

# Расширения файлов для учета
EXTENSIONS = {
    '.go', '.ts', '.tsx', '.js', '.jsx', '.dart', '.proto', 
    '.py', '.sh', '.bash', '.sql', '.yaml', '.yml', '.json',
    '.css', '.scss', '.html', '.md', '.conf', 'Dockerfile'
}

# Исключаемые папки и файлы (сгенерированные, библиотеки, логи, бинарники)
EXCLUDE_DIRS = {
    'node_modules', 'dist', 'build', '.git', '.idea', '.agents',
    '.claude', '.gemini', '.vscode', '.dart_tool', 'gen', 'bin',
    'postgres-data', 'redis-data', 'prometheus-data', 'grafana-data', 'tempo-data',
    '.gradle', 'Pods'
}

EXCLUDE_FILES = {
    'package-lock.json', 'pubspec.lock', 'yarn.lock', 'pnpm-lock.yaml',
    'go.sum', 'main', 'gateway', 'avtoplaneta-backend', 'main.exe',
    'grafana-dashboard.json', 'components.json'
}

def is_generated_content(filepath, content):
    if filepath.endswith('.pb.go') or filepath.endswith('.pb.gw.go'):
        return True
    if 'Code generated by' in content or 'DO NOT EDIT' in content or 'AUTOGENERATED' in content:
        return True
    return False

def count_stats(root_dir):
    stats_by_ext = {}
    stats_by_dir = {}
    
    total_files = 0
    total_lines = 0
    total_code_lines = 0
    total_chars = 0

    for dirpath, dirnames, filenames in os.walk(root_dir):
        dirnames[:] = [d for d in dirnames if d not in EXCLUDE_DIRS and not d.startswith('.')]

        rel_path = os.path.relpath(dirpath, root_dir)
        top_component = rel_path.split(os.sep)[0] if rel_path != '.' else 'root'

        for f in filenames:
            if f in EXCLUDE_FILES or f.endswith('.exe') or f.endswith('.so'):
                continue
            
            ext = os.path.splitext(f)[1]
            if not ext and f in ('Dockerfile', 'Makefile'):
                ext = f
                
            if ext not in EXTENSIONS:
                continue

            filepath = os.path.join(dirpath, f)
            try:
                with open(filepath, 'r', encoding='utf-8', errors='ignore') as file_obj:
                    content = file_obj.read()
                    
                if is_generated_content(filepath, content):
                    continue

                lines = content.splitlines()
                num_lines = len(lines)
                num_chars = len(content)
                
                code_lines = [l for l in lines if l.strip() and not l.strip().startswith('//') and not l.strip().startswith('#') and not l.strip().startswith('/*')]
                num_code_lines = len(code_lines)

                total_files += 1
                total_lines += num_lines
                total_code_lines += num_code_lines
                total_chars += num_chars

                if ext not in stats_by_ext:
                    stats_by_ext[ext] = {'files': 0, 'lines': 0, 'code_lines': 0, 'chars': 0}
                stats_by_ext[ext]['files'] += 1
                stats_by_ext[ext]['lines'] += num_lines
                stats_by_ext[ext]['code_lines'] += num_code_lines
                stats_by_ext[ext]['chars'] += num_chars

                if top_component not in stats_by_dir:
                    stats_by_dir[top_component] = {'files': 0, 'lines': 0, 'code_lines': 0, 'chars': 0}
                stats_by_dir[top_component]['files'] += 1
                stats_by_dir[top_component]['lines'] += num_lines
                stats_by_dir[top_component]['code_lines'] += num_code_lines
                stats_by_dir[top_component]['chars'] += num_chars

            except Exception:
                pass

    return {
        'total_files': total_files,
        'total_lines': total_lines,
        'total_code_lines': total_code_lines,
        'total_chars': total_chars,
        'by_ext': stats_by_ext,
        'by_dir': stats_by_dir
    }

if __name__ == '__main__':
    root_directory = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    results = count_stats(root_directory)
    
    print("=" * 65)
    print("      СТАТИСТИКА ИСХОДНОГО КОДА ПРОЕКТА AVTOPLANETA      ")
    print("=" * 65)
    print(f"Всего авторских файлов:    {results['total_files']:,}")
    print(f"Всего строк (Total Lines): {results['total_lines']:,}")
    print(f"Чистых строк кода (LOC):   {results['total_code_lines']:,}")
    print(f"Всего символов (Chars):    {results['total_chars']:,}")
    print("\n--- Разбор по компонентам ---")
    for comp, data in sorted(results['by_dir'].items(), key=lambda x: x[1]['lines'], reverse=True):
        print(f"  • {comp:<20}: {data['files']:3} файлов | {data['lines']:7,} строк | {data['chars']:10,} символов")
        
    print("\n--- Разбор по языкам / расширениям ---")
    for ext, data in sorted(results['by_ext'].items(), key=lambda x: x[1]['lines'], reverse=True):
        print(f"  • {ext:<12}: {data['files']:3} файлов | {data['lines']:7,} строк | {data['chars']:10,} символов")
    print("=" * 65)
