// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: earnings.sql

package sqlc

import (
	"context"
)

const CreateEarnings = `-- name: CreateEarnings :one
INSERT INTO earnings (total_amount, updated_at) VALUES ($1, NOW()) RETURNING id, total_amount, updated_at
`

func (q *Queries) CreateEarnings(ctx context.Context, totalAmount float64) (Earning, error) {
	row := q.db.QueryRow(ctx, CreateEarnings, totalAmount)
	var i Earning
	err := row.Scan(&i.ID, &i.TotalAmount, &i.UpdatedAt)
	return i, err
}

const GetEarnings = `-- name: GetEarnings :one
SELECT id, total_amount, updated_at FROM earnings ORDER BY id LIMIT 1
`

func (q *Queries) GetEarnings(ctx context.Context) (Earning, error) {
	row := q.db.QueryRow(ctx, GetEarnings)
	var i Earning
	err := row.Scan(&i.ID, &i.TotalAmount, &i.UpdatedAt)
	return i, err
}

const UpdateEarnings = `-- name: UpdateEarnings :exec
UPDATE earnings SET total_amount = $1, updated_at = NOW() WHERE id = $2
`

type UpdateEarningsParams struct {
	TotalAmount float64 `json:"total_amount"`
	ID          int64   `json:"id"`
}

func (q *Queries) UpdateEarnings(ctx context.Context, arg UpdateEarningsParams) error {
	_, err := q.db.Exec(ctx, UpdateEarnings, arg.TotalAmount, arg.ID)
	return err
}

const UpsertEarnings = `-- name: UpsertEarnings :one
INSERT INTO earnings (total_amount, updated_at)
VALUES ($1, NOW())
ON CONFLICT (id) DO UPDATE SET total_amount = $1, updated_at = NOW()
RETURNING id, total_amount, updated_at
`

func (q *Queries) UpsertEarnings(ctx context.Context, totalAmount float64) (Earning, error) {
	row := q.db.QueryRow(ctx, UpsertEarnings, totalAmount)
	var i Earning
	err := row.Scan(&i.ID, &i.TotalAmount, &i.UpdatedAt)
	return i, err
}
