// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: parts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const BulkDeleteByIDs = `-- name: BulkDeleteByIDs :exec
DELETE FROM parts WHERE id = ANY($1::bigint[])
`

func (q *Queries) BulkDeleteByIDs(ctx context.Context, dollar_1 []int64) error {
	_, err := q.db.Exec(ctx, BulkDeleteByIDs, dollar_1)
	return err
}

const CountZeroQuantityBySupplier = `-- name: CountZeroQuantityBySupplier :one
SELECT COUNT(*)::bigint FROM parts
WHERE supplier_code = $1 AND quantity = 0 AND to_delete_at IS NULL AND deleted_at IS NULL
`

func (q *Queries) CountZeroQuantityBySupplier(ctx context.Context, supplierCode string) (int64, error) {
	row := q.db.QueryRow(ctx, CountZeroQuantityBySupplier, supplierCode)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const CreatePart = `-- name: CreatePart :one
INSERT INTO parts (
    name, quantity, description, category, price, salesman, location, address, status,
    brand, model, photos, seller_id, to_delete_at, vin,
    body_brand, engine_brand, car_release_date, front_rear, left_right, top_bottom,
    number, manufacturer, manufacturer_code, oem_code, color, condition,
    supplier_code, defect, transmission, transmission_model, drive, wear_percentage,
    season, diameter, width, profile, tire_quantity, drilling, "offset",
    center_hole_diameter, tire_model, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9,
    $10, $11, $12, $13, $14, $15,
    $16, $17, $18, $19, $20, $21,
    $22, $23, $24, $25, $26, $27,
    $28, $29, $30, $31, $32, $33,
    $34, $35, $36, $37, $38, $39, $40,
    $41, $42, NOW(), NOW()
) RETURNING id, name, quantity, description, category, price, salesman, location, address, status, brand, model, photos, seller_id, to_delete_at, vin, body_brand, engine_brand, car_release_date, front_rear, left_right, top_bottom, number, manufacturer, manufacturer_code, oem_code, color, condition, supplier_code, defect, transmission, transmission_model, drive, wear_percentage, season, diameter, width, profile, tire_quantity, drilling, "offset", center_hole_diameter, tire_model, created_at, updated_at, deleted_at
`

type CreatePartParams struct {
	Name               string             `json:"name"`
	Quantity           int32              `json:"quantity"`
	Description        string             `json:"description"`
	Category           string             `json:"category"`
	Price              float64            `json:"price"`
	Salesman           string             `json:"salesman"`
	Location           string             `json:"location"`
	Address            string             `json:"address"`
	Status             bool               `json:"status"`
	Brand              string             `json:"brand"`
	Model              string             `json:"model"`
	Photos             []byte             `json:"photos"`
	SellerID           int64              `json:"seller_id"`
	ToDeleteAt         pgtype.Timestamptz `json:"to_delete_at"`
	Vin                string             `json:"vin"`
	BodyBrand          string             `json:"body_brand"`
	EngineBrand        string             `json:"engine_brand"`
	CarReleaseDate     string             `json:"car_release_date"`
	FrontRear          string             `json:"front_rear"`
	LeftRight          string             `json:"left_right"`
	TopBottom          string             `json:"top_bottom"`
	Number             string             `json:"number"`
	Manufacturer       string             `json:"manufacturer"`
	ManufacturerCode   string             `json:"manufacturer_code"`
	OemCode            string             `json:"oem_code"`
	Color              string             `json:"color"`
	Condition          string             `json:"condition"`
	SupplierCode       string             `json:"supplier_code"`
	Defect             string             `json:"defect"`
	Transmission       string             `json:"transmission"`
	TransmissionModel  string             `json:"transmission_model"`
	Drive              string             `json:"drive"`
	WearPercentage     string             `json:"wear_percentage"`
	Season             string             `json:"season"`
	Diameter           string             `json:"diameter"`
	Width              string             `json:"width"`
	Profile            string             `json:"profile"`
	TireQuantity       string             `json:"tire_quantity"`
	Drilling           string             `json:"drilling"`
	Offset             string             `json:"offset"`
	CenterHoleDiameter string             `json:"center_hole_diameter"`
	TireModel          string             `json:"tire_model"`
}

func (q *Queries) CreatePart(ctx context.Context, arg CreatePartParams) (Part, error) {
	row := q.db.QueryRow(ctx, CreatePart,
		arg.Name,
		arg.Quantity,
		arg.Description,
		arg.Category,
		arg.Price,
		arg.Salesman,
		arg.Location,
		arg.Address,
		arg.Status,
		arg.Brand,
		arg.Model,
		arg.Photos,
		arg.SellerID,
		arg.ToDeleteAt,
		arg.Vin,
		arg.BodyBrand,
		arg.EngineBrand,
		arg.CarReleaseDate,
		arg.FrontRear,
		arg.LeftRight,
		arg.TopBottom,
		arg.Number,
		arg.Manufacturer,
		arg.ManufacturerCode,
		arg.OemCode,
		arg.Color,
		arg.Condition,
		arg.SupplierCode,
		arg.Defect,
		arg.Transmission,
		arg.TransmissionModel,
		arg.Drive,
		arg.WearPercentage,
		arg.Season,
		arg.Diameter,
		arg.Width,
		arg.Profile,
		arg.TireQuantity,
		arg.Drilling,
		arg.Offset,
		arg.CenterHoleDiameter,
		arg.TireModel,
	)
	var i Part
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Quantity,
		&i.Description,
		&i.Category,
		&i.Price,
		&i.Salesman,
		&i.Location,
		&i.Address,
		&i.Status,
		&i.Brand,
		&i.Model,
		&i.Photos,
		&i.SellerID,
		&i.ToDeleteAt,
		&i.Vin,
		&i.BodyBrand,
		&i.EngineBrand,
		&i.CarReleaseDate,
		&i.FrontRear,
		&i.LeftRight,
		&i.TopBottom,
		&i.Number,
		&i.Manufacturer,
		&i.ManufacturerCode,
		&i.OemCode,
		&i.Color,
		&i.Condition,
		&i.SupplierCode,
		&i.Defect,
		&i.Transmission,
		&i.TransmissionModel,
		&i.Drive,
		&i.WearPercentage,
		&i.Season,
		&i.Diameter,
		&i.Width,
		&i.Profile,
		&i.TireQuantity,
		&i.Drilling,
		&i.Offset,
		&i.CenterHoleDiameter,
		&i.TireModel,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const DecreasePartQuantity = `-- name: DecreasePartQuantity :exec
UPDATE parts
SET quantity = CASE WHEN quantity - $1::integer <= 0 THEN -1 ELSE quantity - $1::integer END
WHERE id = $2
`

type DecreasePartQuantityParams struct {
	Amount int32 `json:"amount"`
	ID     int64 `json:"id"`
}

func (q *Queries) DecreasePartQuantity(ctx context.Context, arg DecreasePartQuantityParams) error {
	_, err := q.db.Exec(ctx, DecreasePartQuantity, arg.Amount, arg.ID)
	return err
}

const DeleteExpiredParts = `-- name: DeleteExpiredParts :execrows
DELETE FROM parts WHERE to_delete_at IS NOT NULL AND to_delete_at <= $1
`

func (q *Queries) DeleteExpiredParts(ctx context.Context, toDeleteAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, DeleteExpiredParts, toDeleteAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const DeletePart = `-- name: DeletePart :exec
DELETE FROM parts WHERE id = $1
`

func (q *Queries) DeletePart(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, DeletePart, id)
	return err
}

const DeleteZeroQuantityBySupplier = `-- name: DeleteZeroQuantityBySupplier :execrows
DELETE FROM parts
WHERE supplier_code = $1 AND quantity = 0 AND to_delete_at IS NULL AND deleted_at IS NULL
`

func (q *Queries) DeleteZeroQuantityBySupplier(ctx context.Context, supplierCode string) (int64, error) {
	result, err := q.db.Exec(ctx, DeleteZeroQuantityBySupplier, supplierCode)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const GetAllParts = `-- name: GetAllParts :many
SELECT id, name, quantity, description, category, price, salesman, location, address, status, brand, model, photos, seller_id, to_delete_at, vin, body_brand, engine_brand, car_release_date, front_rear, left_right, top_bottom, number, manufacturer, manufacturer_code, oem_code, color, condition, supplier_code, defect, transmission, transmission_model, drive, wear_percentage, season, diameter, width, profile, tire_quantity, drilling, "offset", center_hole_diameter, tire_model, created_at, updated_at, deleted_at FROM parts WHERE deleted_at IS NULL ORDER BY id
`

func (q *Queries) GetAllParts(ctx context.Context) ([]Part, error) {
	rows, err := q.db.Query(ctx, GetAllParts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Part{}
	for rows.Next() {
		var i Part
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Quantity,
			&i.Description,
			&i.Category,
			&i.Price,
			&i.Salesman,
			&i.Location,
			&i.Address,
			&i.Status,
			&i.Brand,
			&i.Model,
			&i.Photos,
			&i.SellerID,
			&i.ToDeleteAt,
			&i.Vin,
			&i.BodyBrand,
			&i.EngineBrand,
			&i.CarReleaseDate,
			&i.FrontRear,
			&i.LeftRight,
			&i.TopBottom,
			&i.Number,
			&i.Manufacturer,
			&i.ManufacturerCode,
			&i.OemCode,
			&i.Color,
			&i.Condition,
			&i.SupplierCode,
			&i.Defect,
			&i.Transmission,
			&i.TransmissionModel,
			&i.Drive,
			&i.WearPercentage,
			&i.Season,
			&i.Diameter,
			&i.Width,
			&i.Profile,
			&i.TireQuantity,
			&i.Drilling,
			&i.Offset,
			&i.CenterHoleDiameter,
			&i.TireModel,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetLastCreatedPart = `-- name: GetLastCreatedPart :one
SELECT id, name, quantity, description, category, price, salesman, location, address, status, brand, model, photos, seller_id, to_delete_at, vin, body_brand, engine_brand, car_release_date, front_rear, left_right, top_bottom, number, manufacturer, manufacturer_code, oem_code, color, condition, supplier_code, defect, transmission, transmission_model, drive, wear_percentage, season, diameter, width, profile, tire_quantity, drilling, "offset", center_hole_diameter, tire_model, created_at, updated_at, deleted_at FROM parts WHERE deleted_at IS NULL ORDER BY id DESC LIMIT 1
`

func (q *Queries) GetLastCreatedPart(ctx context.Context) (Part, error) {
	row := q.db.QueryRow(ctx, GetLastCreatedPart)
	var i Part
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Quantity,
		&i.Description,
		&i.Category,
		&i.Price,
		&i.Salesman,
		&i.Location,
		&i.Address,
		&i.Status,
		&i.Brand,
		&i.Model,
		&i.Photos,
		&i.SellerID,
		&i.ToDeleteAt,
		&i.Vin,
		&i.BodyBrand,
		&i.EngineBrand,
		&i.CarReleaseDate,
		&i.FrontRear,
		&i.LeftRight,
		&i.TopBottom,
		&i.Number,
		&i.Manufacturer,
		&i.ManufacturerCode,
		&i.OemCode,
		&i.Color,
		&i.Condition,
		&i.SupplierCode,
		&i.Defect,
		&i.Transmission,
		&i.TransmissionModel,
		&i.Drive,
		&i.WearPercentage,
		&i.Season,
		&i.Diameter,
		&i.Width,
		&i.Profile,
		&i.TireQuantity,
		&i.Drilling,
		&i.Offset,
		&i.CenterHoleDiameter,
		&i.TireModel,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const GetPartByID = `-- name: GetPartByID :one
SELECT id, name, quantity, description, category, price, salesman, location, address, status, brand, model, photos, seller_id, to_delete_at, vin, body_brand, engine_brand, car_release_date, front_rear, left_right, top_bottom, number, manufacturer, manufacturer_code, oem_code, color, condition, supplier_code, defect, transmission, transmission_model, drive, wear_percentage, season, diameter, width, profile, tire_quantity, drilling, "offset", center_hole_diameter, tire_model, created_at, updated_at, deleted_at FROM parts WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPartByID(ctx context.Context, id int64) (Part, error) {
	row := q.db.QueryRow(ctx, GetPartByID, id)
	var i Part
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Quantity,
		&i.Description,
		&i.Category,
		&i.Price,
		&i.Salesman,
		&i.Location,
		&i.Address,
		&i.Status,
		&i.Brand,
		&i.Model,
		&i.Photos,
		&i.SellerID,
		&i.ToDeleteAt,
		&i.Vin,
		&i.BodyBrand,
		&i.EngineBrand,
		&i.CarReleaseDate,
		&i.FrontRear,
		&i.LeftRight,
		&i.TopBottom,
		&i.Number,
		&i.Manufacturer,
		&i.ManufacturerCode,
		&i.OemCode,
		&i.Color,
		&i.Condition,
		&i.SupplierCode,
		&i.Defect,
		&i.Transmission,
		&i.TransmissionModel,
		&i.Drive,
		&i.WearPercentage,
		&i.Season,
		&i.Diameter,
		&i.Width,
		&i.Profile,
		&i.TireQuantity,
		&i.Drilling,
		&i.Offset,
		&i.CenterHoleDiameter,
		&i.TireModel,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const GetPartsForXML = `-- name: GetPartsForXML :many
SELECT id, name, quantity, description, category, price, salesman, location, address, status, brand, model, photos, seller_id, to_delete_at, vin, body_brand, engine_brand, car_release_date, front_rear, left_right, top_bottom, number, manufacturer, manufacturer_code, oem_code, color, condition, supplier_code, defect, transmission, transmission_model, drive, wear_percentage, season, diameter, width, profile, tire_quantity, drilling, "offset", center_hole_diameter, tire_model, created_at, updated_at, deleted_at FROM parts WHERE to_delete_at IS NULL AND quantity >= 0 AND deleted_at IS NULL ORDER BY id
`

func (q *Queries) GetPartsForXML(ctx context.Context) ([]Part, error) {
	rows, err := q.db.Query(ctx, GetPartsForXML)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Part{}
	for rows.Next() {
		var i Part
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Quantity,
			&i.Description,
			&i.Category,
			&i.Price,
			&i.Salesman,
			&i.Location,
			&i.Address,
			&i.Status,
			&i.Brand,
			&i.Model,
			&i.Photos,
			&i.SellerID,
			&i.ToDeleteAt,
			&i.Vin,
			&i.BodyBrand,
			&i.EngineBrand,
			&i.CarReleaseDate,
			&i.FrontRear,
			&i.LeftRight,
			&i.TopBottom,
			&i.Number,
			&i.Manufacturer,
			&i.ManufacturerCode,
			&i.OemCode,
			&i.Color,
			&i.Condition,
			&i.SupplierCode,
			&i.Defect,
			&i.Transmission,
			&i.TransmissionModel,
			&i.Drive,
			&i.WearPercentage,
			&i.Season,
			&i.Diameter,
			&i.Width,
			&i.Profile,
			&i.TireQuantity,
			&i.Drilling,
			&i.Offset,
			&i.CenterHoleDiameter,
			&i.TireModel,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetStatsCategories = `-- name: GetStatsCategories :many
SELECT category AS name, COUNT(*)::bigint AS count
FROM parts
WHERE to_delete_at IS NULL AND quantity >= 1 AND deleted_at IS NULL AND category != ''
GROUP BY category
ORDER BY count DESC
`

type GetStatsCategoriesRow struct {
	Name  string `json:"name"`
	Count int64  `json:"count"`
}

func (q *Queries) GetStatsCategories(ctx context.Context) ([]GetStatsCategoriesRow, error) {
	rows, err := q.db.Query(ctx, GetStatsCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStatsCategoriesRow{}
	for rows.Next() {
		var i GetStatsCategoriesRow
		if err := rows.Scan(&i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetStatsTotals = `-- name: GetStatsTotals :one
SELECT
    COUNT(*)::bigint AS total_parts,
    COALESCE(SUM(quantity), 0)::bigint AS total_quantity,
    COALESCE(SUM(price * quantity), 0)::float8 AS total_value
FROM parts
WHERE to_delete_at IS NULL AND quantity >= 1 AND deleted_at IS NULL
`

type GetStatsTotalsRow struct {
	TotalParts    int64   `json:"total_parts"`
	TotalQuantity int64   `json:"total_quantity"`
	TotalValue    float64 `json:"total_value"`
}

func (q *Queries) GetStatsTotals(ctx context.Context) (GetStatsTotalsRow, error) {
	row := q.db.QueryRow(ctx, GetStatsTotals)
	var i GetStatsTotalsRow
	err := row.Scan(&i.TotalParts, &i.TotalQuantity, &i.TotalValue)
	return i, err
}

const GetSupplierCodes = `-- name: GetSupplierCodes :many
SELECT DISTINCT supplier_code FROM parts
WHERE supplier_code IS NOT NULL AND supplier_code != '' AND quantity = 0 AND to_delete_at IS NULL AND deleted_at IS NULL
ORDER BY supplier_code
`

func (q *Queries) GetSupplierCodes(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, GetSupplierCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var supplier_code string
		if err := rows.Scan(&supplier_code); err != nil {
			return nil, err
		}
		items = append(items, supplier_code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const IncreasePartQuantity = `-- name: IncreasePartQuantity :exec
UPDATE parts
SET quantity = CASE WHEN quantity = -1 THEN $1::integer ELSE quantity + $1::integer END
WHERE id = $2
`

type IncreasePartQuantityParams struct {
	Amount int32 `json:"amount"`
	ID     int64 `json:"id"`
}

func (q *Queries) IncreasePartQuantity(ctx context.Context, arg IncreasePartQuantityParams) error {
	_, err := q.db.Exec(ctx, IncreasePartQuantity, arg.Amount, arg.ID)
	return err
}

const MarkForDeletion = `-- name: MarkForDeletion :exec
UPDATE parts SET to_delete_at = $2, updated_at = NOW() WHERE id = $1
`

type MarkForDeletionParams struct {
	ID         int64              `json:"id"`
	ToDeleteAt pgtype.Timestamptz `json:"to_delete_at"`
}

func (q *Queries) MarkForDeletion(ctx context.Context, arg MarkForDeletionParams) error {
	_, err := q.db.Exec(ctx, MarkForDeletion, arg.ID, arg.ToDeleteAt)
	return err
}

const SoftDeletePart = `-- name: SoftDeletePart :exec
UPDATE parts SET deleted_at = NOW() WHERE id = $1
`

func (q *Queries) SoftDeletePart(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, SoftDeletePart, id)
	return err
}

const UpdatePartPhotos = `-- name: UpdatePartPhotos :exec
UPDATE parts SET photos = $2, updated_at = NOW() WHERE id = $1
`

type UpdatePartPhotosParams struct {
	ID     int64  `json:"id"`
	Photos []byte `json:"photos"`
}

func (q *Queries) UpdatePartPhotos(ctx context.Context, arg UpdatePartPhotosParams) error {
	_, err := q.db.Exec(ctx, UpdatePartPhotos, arg.ID, arg.Photos)
	return err
}
