/*
 * Copyright (c) 2025 Avtoplaneta. All rights reserved.
 */

import type { SelectOption } from "@/components/ui/searchable-select";

export const brandOptions: SelectOption[] = [
  { value: "Acura", label: "Acura" },
  { value: "Alfa Romeo", label: "Alfa Romeo" },
  { value: "Aston Martin", label: "Aston Martin" },
  { value: "Audi", label: "Audi" },
  { value: "BAIC", label: "BAIC" },
  { value: "Bentley", label: "Bentley" },
  { value: "BMW", label: "BMW" },
  { value: "Buick", label: "Buick" },
  { value: "BYD", label: "BYD" },
  { value: "Cadillac", label: "Cadillac" },
  { value: "Changan", label: "Changan" },
  { value: "Chery", label: "Chery" },
  { value: "Chevrolet", label: "Chevrolet" },
  { value: "Chrysler", label: "Chrysler" },
  { value: "Citroen", label: "Citroën" },
  { value: "DAF", label: "DAF" },
  { value: "Daihatsu", label: "Daihatsu" },
  { value: "Datsun", label: "Datsun" },
  { value: "Dodge", label: "Dodge" },
  { value: "Dongfeng", label: "Dongfeng" },
  { value: "Exeed", label: "Exeed" },
  { value: "FAW", label: "FAW" },
  { value: "Ferrari", label: "Ferrari" },
  { value: "Fiat", label: "Fiat" },
  { value: "Ford", label: "Ford" },
  { value: "GAC", label: "GAC" },
  { value: "Geely", label: "Geely" },
  { value: "Genesis", label: "Genesis" },
  { value: "GMC", label: "GMC" },
  { value: "Great Wall", label: "Great Wall" },
  { value: "Haval", label: "Haval" },
  { value: "Hino", label: "Hino" },
  { value: "Honda", label: "Honda" },
  { value: "Hongqi", label: "Hongqi" },
  { value: "Hummer", label: "Hummer" },
  { value: "Hyundai", label: "Hyundai" },
  { value: "Infiniti", label: "Infiniti" },
  { value: "Isuzu", label: "Isuzu" },
  { value: "Iveco", label: "Iveco" },
  { value: "JAC", label: "JAC" },
  { value: "Jaecoo", label: "Jaecoo" },
  { value: "Jaguar", label: "Jaguar" },
  { value: "Jeep", label: "Jeep" },
  { value: "Jetour", label: "Jetour" },
  { value: "Kaiyi", label: "Kaiyi" },
  { value: "Kenworth", label: "Kenworth" },
  { value: "Kia", label: "Kia" },
  { value: "Lada", label: "Lada (ВАЗ)" },
  { value: "Lamborghini", label: "Lamborghini" },
  { value: "Land Rover", label: "Land Rover" },
  { value: "Lexus", label: "Lexus" },
  { value: "Li Auto", label: "Li Auto (Lixiang)" },
  { value: "Lifan", label: "Lifan" },
  { value: "Lincoln", label: "Lincoln" },
  { value: "Mack", label: "Mack" },
  { value: "MAN", label: "MAN" },
  { value: "Maserati", label: "Maserati" },
  { value: "Mazda", label: "Mazda" },
  { value: "Mercedes", label: "Mercedes-Benz" },
  { value: "Mercedes-Benz Trucks", label: "Mercedes-Benz Trucks" },
  { value: "Mini", label: "Mini" },
  { value: "Mitsubishi", label: "Mitsubishi" },
  { value: "Moskvich", label: "Москвич" },
  { value: "Nissan", label: "Nissan" },
  { value: "Omoda", label: "Omoda" },
  { value: "Opel", label: "Opel" },
  { value: "Peterbilt", label: "Peterbilt" },
  { value: "Peugeot", label: "Peugeot" },
  { value: "Porsche", label: "Porsche" },
  { value: "Ram", label: "Ram" },
  { value: "Ravon", label: "Ravon" },
  { value: "Renault", label: "Renault" },
  { value: "Rolls-Royce", label: "Rolls-Royce" },
  { value: "Saab", label: "Saab" },
  { value: "Scania", label: "Scania" },
  { value: "Seat", label: "Seat" },
  { value: "Skoda", label: "Škoda" },
  { value: "Smart", label: "Smart" },
  { value: "SsangYong", label: "SsangYong" },
  { value: "Subaru", label: "Subaru" },
  { value: "Suzuki", label: "Suzuki" },
  { value: "Tank", label: "Tank" },
  { value: "Tesla", label: "Tesla" },
  { value: "Toyota", label: "Toyota" },
  { value: "UAZ", label: "УАЗ" },
  { value: "UD Trucks", label: "UD Trucks" },
  { value: "Volkswagen", label: "Volkswagen" },
  { value: "Volvo", label: "Volvo" },
  { value: "Volvo Trucks", label: "Volvo Trucks" },
  { value: "Vortex", label: "Vortex" },
  { value: "Voyah", label: "Voyah" },
  { value: "Western Star", label: "Western Star" },
  { value: "Zeekr", label: "Zeekr" },
];
